import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import {Provider} from "@/components/Provider";
import {MicrosoftClarity} from "@/components/Clarity";
import {GoogleAnalytics} from "@next/third-parties/google";

const rubikMono = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const getVoip = localFont({
  src: "../fonts/GetVoIP-Grotesque.otf",
  variable: "--font-getvoip",
  weight: "400",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="uk"
      className={`${rubikMono.variable} ${getVoip.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-rubik bg-[rgba(230,230,230,1)]">
      <Provider>
        {children}
      </Provider>
      <MicrosoftClarity/>
      {process.env.NEXT_PUBLIC_GA_ID && (
          <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID} />
      )}
      </body>
    </html>
  );
}
